DROP TABLE IF EXISTS posts;
CREATE TABLE posts(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, body TEXT, image TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TRIGGER timestamp_update BEFORE UPDATE ON posts BEGIN
		UPDATE post SET update_at = CURRENT_TIMESTAMP WHERE id = new.id;
		END;
